---
title: "ApptoValidMobileConversionAnalysis"
author: "Dhivya R"
date: "2/9/2017"
output: html_document
---

## Base Rate- App to ValidMobile for Dec 2016- Jan 2017 PL
```{r setup, include=FALSE, echo=FALSE}
setwd("/home/dhivya/Risk/Relaunch")
options(warn=-1)
load("/home/dhivya/Risk/Relaunch/FreshNew_PL.RData")
load("/home/dhivya/Risk/Relaunch/Freshnew_CC.RData")
source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
table(all$Applied)[2]/table(all$isValidMobile)[2]*100
```

## No Offer Rate- No Offers to Searches
```{r, echo=FALSE}
table(all$bank_id)[1]/length(unique(all$eligibility_id))*100
```

## % of offers with valid mobile is high at 40.62% for HDBFS, 19.06% for Fullerton, 17.08% for ICICI and extremely low at 2.35% for Oriental Bank of Commerce and 3.84% for IndusInd
```{r, echo=FALSE}
df <- all[all$bank_id!=0,]
df <- all[all$partner==1,]
case <- ddply(df[,c("eligibility_id","bank_id","bank_name","isValidMobile","bank_name","Applied")],.(eligibility_id), summarize, PartnerOffers=length(unique(bank_id)), ValidMobile=sum(isValidMobile),  Banks=paste(bank_name,collapse=","), AppliedCount=sum(Applied))
crosstab(df, row.vars = "bank_name", col.vars = "isValidMobile", type = c("f","r"))
```

